Update roadmap content
arcana-network/website pull request #86
Opened 2022-02-09 11:20 UTC by KarthikSiddarth

# Resolves

- [AR-1508](https://team-1624093970686.atlassian.net/browse/AR-1508)

## Changes

Added 2022 roadmap content.

# Screenshots
## Mobile
<img width="327" alt="Screenshot 2022-02-09 at 4 47 15 PM" src="https://user-images.githubusercontent.com/40512676/153189658-64605499-9649-4c48-a382-ccee7c371e72.png">

## Desktop
<img width="1440" alt="Screenshot 2022-02-09 at 4 49 42 PM" src="https://user-images.githubusercontent.com/40512676/153189846-33c49ae5-85f5-4f3a-a24e-fc62f93bf2de.png">

# Checklist

- [X] The branch name follows the format: `developer-name/AR-XXX-issue-name`.
- [X] The changes have been tested locally.

2022-02-09 12:00 UTC, ajithranka requested changes

2022-02-10 03:27 UTC, KarthikSiddarth commented on components/tech/RoadmapList.vue
> +  /* border: 1px solid red; */
no, will remove it

2022-02-10 03:29 UTC, KarthikSiddarth commented on components/tech/RoadmapList.vue
> +  /* border: 1px solid red; */
removed. [commit](https://github.com/arcana-network/website/pull/86/commits/d72ba34e93f0f394912abcda94a61c9f12b7f3f0)

2022-02-10 03:34 UTC, shrinathprabhu approved these changes

2022-02-10 05:12 UTC, ajithranka approved these changes

2022-02-10 05:48 UTC, merged